version: '3.9'

services:
    #PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: digitalocean.com/php
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravel
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes:
            - ./:/var/www/html/live-stream-docker
        ports:
            - "9000:9000"
        networks:
            - laravel

#    Nginx Service
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html/live-stream-docker
            - ./docker-files/nginx/default.conf/:/etc/nginx/conf.d/default.conf
        networks:
            - laravel

#    MySQL Service
#    mysql:
#        image: mysql:5.7.22
#        container_name: db
#        restart: unless-stopped
#        tty: true
#        ports:
#            - "4306:3306"
#        environment:
#            MYSQL_DATABASE: database_name
#            MYSQL_USER: user
#            MYSQL_PASSWORD: password
#            MYSQL_ROOT_PASSWORD: root
#            SERVICE_TAGS: dev
#            SERVICE_NAME: mysql
#        volumes:
#            - ./docker-files/mysql:/var/lib/mysql
#        networks:
#            - laravel

    #RTMP service
    rtmp:
        build: ./rtmp
        ports:
            - "1935:1935"
            - "8080:8080"
        container_name: rtmp_server
        volumes:
            - ./data:/tmp/hls
    auth:
        build: ./auth
        container_name: auth_server
#Docker Networks
networks:
    laravel:
        driver: bridge
#Volumes
volumes:
    dbdata:
        driver: local
